language: node_js
node_js:
    - '14'
cache:
    directories:
        - node_modules
install:
    - npm install
script:
    - npm run lint
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - npm run build -- --prod --base-href /froggy/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/froggy
    target_branch: gh-pages
    on:
        branch: main
